### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mimipeshy** [carlos-ssh/tnw-page#1]
Hi Carlos,
Amazing work you did with the desktop version, the site looks almost identical to the real one.  A few pointers to note ✍️ 

-  The mobile view approach first is recommended, it will save you a lot of time trying to align-items

- Make use of vh and vw for your widths and height as they are responsive as compared to using px

- Fix the overflow in your container, it might be caused by images that are overflowing. Use the pointers i mentioned above. 

We wish you all the best Carlos!  Happy coding 💻 🖱️ 💯 
Kind Regards,
Peris Ndanu.

**Comment by carlos-ssh** [comment]
Thank you, Peris, for your review. We gonna start to fix these issues and take part in your recommendations.
