### ISSUE TITLE
June 26th Review

### ISSUE THREAD

**Issue by eliasecasta** [carlos-ssh/tnw-page#11]
Hello Carlos, you are almost there, try implementing this changes: 

- Set img{width: 100%} for all your images so you can have a correct display of them in all your webpage and all your viewports.
- Try to not use px for everything, you should use measures that dynamically scale like %, em, rem, vw and vh.

Good luck!

**Comment by carlos-ssh** [comment]
Ok, we will work on this! thanks a lot!
