### ISSUE TITLE
Peer to peer review 30-06-2020

### ISSUE THREAD

**Issue by mikethreels** [carlos-ssh/tnw-page#12]
Hi Carlos,

your project is looking better and better you're almost there, here are some tips for you to move forward.
- try to use semantics HTML5
- it will be very difficult to make changes the more lines of CSS you have.
- a lot of your sections are overlapping your viewport
- try to use minmax with grid

You are really close to finishing the project, don't give up.

greetings
team-122-the-manx

**Comment by carlos-ssh** [comment]
Alright, thanks for the recommendation we will work on this to have a much better project.
