### ISSUE TITLE
06/19/2020

### ISSUE THREAD

**Issue by Victorgonbu** [carlos-ssh/tnw-page#6]
Hi Carlos, your project is looking Awesome! for the responsive issue:

- Check container's widths, there are a lot of static widths(pxls), maybe those are the reason for the responsive issue,  instead, try to use relative measurements (em, fr, %, vh, vw, Try to play with them a little bit).

**Comment by carlos-ssh** [comment]
Thanks a lot for the retrospection! we're working to fix ;D
